"""
This type stub file was generated by pyright.
"""

import sys
import platform

if sys.platform.startswith("win"):
    _HandlerRoutine = ...
    _callback = ...
else:
    ...
_absolute_path_sesum = ...
_shared_lib_dir = ...
_lib_psr_name = ...
_clibrary = ...
_BaseClassOpt = ...
class CGreedy(_BaseClassOpt):
    def __init__(self, seed=..., minimize=..., algorithm=..., skops_alpha=..., max_repeats=..., max_time=..., progbar=..., is_outer_optimal=..., threshold_optimal=..., threads=..., is_linear=...) -> None:
        """
         Initialize the CGreedy optimizer.

         Parameters:
         ----------
         seed : int, optional
             Random seed for reproducibility. Default is 0.

         minimize : str, optional
             Criterion to minimize. Either 'size', 'flops' or 'b-flops'. Default is 'size'.

         algorithm : str, optional
             Algorithm for computing the contraction path. Either 'greedy' or 'kahypar'. Default is 'greedy'.

         skops_alpha : float, optional
             Adjusts pairwise flops computations in tensor contractions by adding
             skops_alpha * abs(sizeA - sizeB) * log10(flops). Aims to emphasize tensor size disparities' impact,
             with higher values penalizing size mismatches more. Default is 0.0.

         max_repeats : int, optional
             Maximum number of times the optimization can be repeated. Default is 8.

         max_time : float, optional
             Maximum time (in seconds) the optimizer is allowed to run. If set to 0.0 or less,
             there's no time limit. Default is 0.0.

         progbar : bool, optional
             Whether to display a progress bar during optimization. Default is False.

         is_outer_optimal: bool, optional
             Whether to consider outer products in the optimal search. Default is False.

         threshold_optimal: uint, optional
             Maximum number of input tensors to perform an expensive optimal search instead
             of a greedy search. Default is 12.

         threads : uint, optional
             Number of threads to be used for the greedy algorithm. Default is 0.
             (Setting the value to 0 uses all available threads.)

         is_linear : bool, optional
            Whether to compute a path in linear format or SSA format. Default is True.

         Raises:
         ------
         Exception:
             If the 'minimize' parameter is not either 'size', 'flops' or 'b-flops'.

         Attributes:
         -----------
         flops_log10 : float
             Log base 10 of the number of flops (floating-point operations). Initialized to negative infinity.
             This value is updated after the algorithm is executed.

         size_log2 : float
             Log base 2 of the biggest intermediate tensor size. Initialized to negative infinity.
             This value is updated after the algorithm is executed.

         path_time : float
             Time (in seconds) used internally to compute the contraction path. Initialized to negative infinity.
             This value is updated after the algorithm is executed.

         """
        ...
    
    def __call__(self, inputs, output, sizes, memory_limit=...) -> tuple[Literal[0]] | list[Any]:
        ...
    


def compute_path(format_string, *arguments, seed=..., minimize=..., algorithm=..., skops_alpha=..., max_repeats=..., max_time=..., progbar=..., is_outer_optimal=..., threshold_optimal=..., threads=..., is_linear=...) -> tuple[list[tuple[Literal[0]]] | list[Any], float, float]:
    """
    Compute the contraction path for a given format string and tensor shapes.

    Parameters:
    ----------
    format_string : str
        The format string specifying the contraction. For example, "ij,jk->ik".

    *arguments : numpy.ndarray or list or tuple
        Shapes of tensors involved in the contraction. They can be provided as numpy arrays, lists, or tuples.

    seed : int, optional
        Random seed for reproducibility. Default is 0.

    minimize : str, optional
        Criterion to minimize during contraction. Either 'size', 'flops' or 'b-flops'. Default is 'size'.

    algorithm : str, optional
        Algorithm for computing the contraction path. Either 'greedy' or 'kahypar'. Default is 'greedy'.

    skops_alpha : float, optional
        Adjusts pairwise flops computations in tensor contractions by adding
        skops_alpha * abs(sizeA - sizeB) * log10(flops). Aims to emphasize tensor size disparities' impact,
        with higher values penalizing size mismatches more. Default is 0.0.

    max_repeats : uint, optional
        Maximum number of times the optimization can be repeated. Default is 8.

    max_time : float, optional
        Maximum time (in seconds) the optimizer is allowed to run. If set to 0.0 or less,
        there's no time limit. Default is 0.0.

    progbar : bool, optional
        Whether to display a progress bar during optimization. Default is False.

    is_outer_optimal : bool, optional
        Whether to consider outer products in the optimal search. Default is False.

    threshold_optimal : uint, optional
        Maximum number of input tensors to perform an expensive optimal search instead
        of a greedy search. Default is 12.

    threads : uint, optional
       Number of threads to be used for the greedy algorithm. Default is 0.
       (Setting the value to 0 uses all available threads.)

    is_linear : bool, optional
       Whether to compute a path in linear format or SSA format. Default is True.

    Returns:
    -------
    tuple
        A tuple containing:
        - contraction path as a list of pairwise contraction.
        - Log base 10 of the number of flops (floating-point operations).
        - Log base 2 of the biggest intermediate tensor size.

    Notes:
    -----
    The format string should be in the form "input->output", where 'input' is a comma-separated list of tensor indices,
    and 'output' is the desired contraction output tensor indices.

    The input tensor shapes can be provided in multiple ways, including numpy arrays, lists, or tuples.

    Example:
    -------
    >>> compute_path("ij,jk->ik", (2,3), (3,4))
    """
    ...

class _Tag:
    """A simple class to represent a type tag."""
    def __init__(self, name) -> None:
        ...
    
    def __repr__(self) -> Any:
        ...
    


bigint = ...
int128 = ...
uint128 = ...
standard = ...
max_plus = ...
def sesum(format_string, *arguments, path=..., dtype=..., debug=..., safe_convert=..., backend=..., semiring=...):
    """
    This function contracts tensors according to the given format string.

    Parameters:
    ----------
    format_string : str
        The format string specifying the contraction. For example, "ij,jk->ik".

    *arguments : numpy.ndarray(s)
        Input tensors involved in the contraction.

    path : list of tuples, optional
        Sequence of pairwise tensor contractions, where each tuple defines which tensors to contract.
        If not provided, it will be computed automatically. Default is None.

    dtype : numpy dtype or property method, optional
        Data type of the result tensor. Supported data types include:
        - Floating Point: np.float64, np.float32
        - Complex Numbers: np.csingle, np.cdouble
        - Integers: np.int8, np.int16, np.int32, np.int64
        - Unsigned Integers: np.uint8, np.uint16, np.uint32, np.uint64
        - Special Types: bigint, int128, uint128
        Default is None, in which case it is inferred.

    debug : bool, optional
        If set to True, additional debugging information will be printed while executing. Default is False.

    safe_convert : bool, optional
        If True, ensures input data conversion to the final data type is overflow-free. Default is False.
        Note: This does not check for overflow during computation.

    backend : str, optional
        Backend used for tensor contractions. Valid values are "dense" and "sparse". Default is "dense".

    semiring : enum, optional
        Specifies the semiring to be used. Valid values are 'standard' and 'max_plus'. Default is 'standard'.

    Returns:
    -------
    numpy.ndarray
        Resulting tensor from the contraction.

    Raises:
    ------
    ValueError:
        If there's any inconsistency in the format string or input tensors.

    Exception:
        For unsupported data types or backends.

    Notes:
    -----
    The format string should be in the form "input->output", where 'input' is a comma-separated list of tensor indices,
    and 'output' is the desired contraction output tensor indices.

    Example:
    -------
    >>> a = np.array([[1,2],[3,4]])
    >>> b = np.array([[1,1],[1,1]])
    >>> sesum("ij,jk->ik", a, b)
    array([[3., 3.],
           [7., 7.]])
    """
    ...

